##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# Task to check if Pod is terminated
# This task will try for a maximum of 10 times with an interval of
# 60 seconds between each try

- name: Delete pod controlled by StatefulSet
  tasks:
    - name: Scale down StatefulSet to 0 replicas
      kubernetes.core.k8s:
        state: present
        kind: StatefulSet
        name: fabric-peernode-peer1
        namespace: warehouse-net
        replicas: 0
        kubeconfig: "{{ kubeconfig | default(kubernetes.config_file) }}"
        context: "{{ context | default(kubernetes.context) }}"
      register: statefulset_scaledown
      retries: 3
      delay: 10
      until: statefulset_scaledown.changed

    - name: Delete the pod fabric-peernode-peer1-0
      kubernetes.core.k8s:
        state: absent
        kind: Pod
        name: "fabric-peernode-peer1-0"
        namespace: "warehouse-net"
        kubeconfig: "{{ kubeconfig | default(kubernetes.config_file) }}"
        context: "{{ context | default(kubernetes.context) }}"
      register: pod_deleted
      retries: 3
      delay: 10
      until: pod_deleted.changed

    - name: Verify the pod is deleted
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: warehouse-net
        kubeconfig: "{{ kubeconfig | default(kubernetes.config_file) }}"
        context: "{{ context | default(kubernetes.context) }}"
        label_selectors:
          app: fabric-peernode-peer1
      register: pod_verification
      retries: 3
      delay: 10
      until: pod_verification.resources | length == 0
