##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# This task initiates cli creation and signing of the block
############################################################################################

# Fetch the modified config block from build and the admin signs the config block
# Copy the block back to the build folder after signature
- name: Signing from the admin of {{ org.name }}
  shell: |
    export PEER_CLI=$(KUBECONFIG={{ kubernetes.config_file }} kubectl get po -n {{ org.name | lower }}-net | grep "cli" | head -n 1 | awk '{print $1}')
    KUBECONFIG={{ kubernetes.config_file }} kubectl cp ./build/{{ channel_name | lower}}_config_block.pb {{ org.name | lower }}-net/${PEER_CLI}:/opt/gopath/src/github.com/hyperledger/fabric/peer/{{ channel_name | lower}}_config_block.pb
    KUBECONFIG={{ kubernetes.config_file }} kubectl exec -n {{ org.name | lower }}-net ${PEER_CLI} -- peer channel signconfigtx -f {{ channel_name | lower}}_config_block.pb
    KUBECONFIG={{ kubernetes.config_file }} kubectl cp {{ org.name | lower }}-net/${PEER_CLI}:/opt/gopath/src/github.com/hyperledger/fabric/peer/{{ channel_name | lower}}_config_block.pb ./build/{{ channel_name | lower}}_config_block.pb
  vars: 
    kubernetes: "{{ org.k8s }}"

